name: dart_application_20
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  austerity: ^1.2.0

dev_dependencies:
  collection: ^1.19.0
  lints: ^2.1.0
  test: ^1.24.0
